// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Task.proto

package com.cloudmap.message;

public final class TaskMessage {
  private TaskMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaskOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 taskId = 1;
    /**
     * <code>required int64 taskId = 1;</code>
     */
    boolean hasTaskId();
    /**
     * <code>required int64 taskId = 1;</code>
     */
    long getTaskId();

    // required int64 clientId = 2;
    /**
     * <code>required int64 clientId = 2;</code>
     */
    boolean hasClientId();
    /**
     * <code>required int64 clientId = 2;</code>
     */
    long getClientId();

    // optional int64 workerId = 3;
    /**
     * <code>optional int64 workerId = 3;</code>
     */
    boolean hasWorkerId();
    /**
     * <code>optional int64 workerId = 3;</code>
     */
    long getWorkerId();

    // required string taskType = 4;
    /**
     * <code>required string taskType = 4;</code>
     */
    boolean hasTaskType();
    /**
     * <code>required string taskType = 4;</code>
     */
    java.lang.String getTaskType();
    /**
     * <code>required string taskType = 4;</code>
     */
    com.google.protobuf.ByteString
        getTaskTypeBytes();

    // required string bucketName = 5;
    /**
     * <code>required string bucketName = 5;</code>
     */
    boolean hasBucketName();
    /**
     * <code>required string bucketName = 5;</code>
     */
    java.lang.String getBucketName();
    /**
     * <code>required string bucketName = 5;</code>
     */
    com.google.protobuf.ByteString
        getBucketNameBytes();

    // required string splitName = 6;
    /**
     * <code>required string splitName = 6;</code>
     */
    boolean hasSplitName();
    /**
     * <code>required string splitName = 6;</code>
     */
    java.lang.String getSplitName();
    /**
     * <code>required string splitName = 6;</code>
     */
    com.google.protobuf.ByteString
        getSplitNameBytes();

    // optional string responseQueueUrl = 7;
    /**
     * <code>optional string responseQueueUrl = 7;</code>
     */
    boolean hasResponseQueueUrl();
    /**
     * <code>optional string responseQueueUrl = 7;</code>
     */
    java.lang.String getResponseQueueUrl();
    /**
     * <code>optional string responseQueueUrl = 7;</code>
     */
    com.google.protobuf.ByteString
        getResponseQueueUrlBytes();

    // optional int64 sendTime = 8;
    /**
     * <code>optional int64 sendTime = 8;</code>
     */
    boolean hasSendTime();
    /**
     * <code>optional int64 sendTime = 8;</code>
     */
    long getSendTime();

    // optional int64 receiveTime = 9;
    /**
     * <code>optional int64 receiveTime = 9;</code>
     */
    boolean hasReceiveTime();
    /**
     * <code>optional int64 receiveTime = 9;</code>
     */
    long getReceiveTime();

    // optional int64 completeTime = 10;
    /**
     * <code>optional int64 completeTime = 10;</code>
     */
    boolean hasCompleteTime();
    /**
     * <code>optional int64 completeTime = 10;</code>
     */
    long getCompleteTime();

    // optional int64 finishTime = 11;
    /**
     * <code>optional int64 finishTime = 11;</code>
     */
    boolean hasFinishTime();
    /**
     * <code>optional int64 finishTime = 11;</code>
     */
    long getFinishTime();
  }
  /**
   * Protobuf type {@code Task}
   */
  public static final class Task extends
      com.google.protobuf.GeneratedMessage
      implements TaskOrBuilder {
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Task(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Task defaultInstance;
    public static Task getDefaultInstance() {
      return defaultInstance;
    }

    public Task getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              taskId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              workerId_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              taskType_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              bucketName_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              splitName_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              responseQueueUrl_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              sendTime_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              receiveTime_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              completeTime_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              finishTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudmap.message.TaskMessage.internal_static_Task_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudmap.message.TaskMessage.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudmap.message.TaskMessage.Task.class, com.cloudmap.message.TaskMessage.Task.Builder.class);
    }

    public static com.google.protobuf.Parser<Task> PARSER =
        new com.google.protobuf.AbstractParser<Task>() {
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Task(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 taskId = 1;
    public static final int TASKID_FIELD_NUMBER = 1;
    private long taskId_;
    /**
     * <code>required int64 taskId = 1;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 taskId = 1;</code>
     */
    public long getTaskId() {
      return taskId_;
    }

    // required int64 clientId = 2;
    public static final int CLIENTID_FIELD_NUMBER = 2;
    private long clientId_;
    /**
     * <code>required int64 clientId = 2;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 clientId = 2;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    // optional int64 workerId = 3;
    public static final int WORKERID_FIELD_NUMBER = 3;
    private long workerId_;
    /**
     * <code>optional int64 workerId = 3;</code>
     */
    public boolean hasWorkerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 workerId = 3;</code>
     */
    public long getWorkerId() {
      return workerId_;
    }

    // required string taskType = 4;
    public static final int TASKTYPE_FIELD_NUMBER = 4;
    private java.lang.Object taskType_;
    /**
     * <code>required string taskType = 4;</code>
     */
    public boolean hasTaskType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string taskType = 4;</code>
     */
    public java.lang.String getTaskType() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taskType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskTypeBytes() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string bucketName = 5;
    public static final int BUCKETNAME_FIELD_NUMBER = 5;
    private java.lang.Object bucketName_;
    /**
     * <code>required string bucketName = 5;</code>
     */
    public boolean hasBucketName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string bucketName = 5;</code>
     */
    public java.lang.String getBucketName() {
      java.lang.Object ref = bucketName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bucketName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bucketName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBucketNameBytes() {
      java.lang.Object ref = bucketName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucketName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string splitName = 6;
    public static final int SPLITNAME_FIELD_NUMBER = 6;
    private java.lang.Object splitName_;
    /**
     * <code>required string splitName = 6;</code>
     */
    public boolean hasSplitName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string splitName = 6;</code>
     */
    public java.lang.String getSplitName() {
      java.lang.Object ref = splitName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          splitName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string splitName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSplitNameBytes() {
      java.lang.Object ref = splitName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        splitName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string responseQueueUrl = 7;
    public static final int RESPONSEQUEUEURL_FIELD_NUMBER = 7;
    private java.lang.Object responseQueueUrl_;
    /**
     * <code>optional string responseQueueUrl = 7;</code>
     */
    public boolean hasResponseQueueUrl() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string responseQueueUrl = 7;</code>
     */
    public java.lang.String getResponseQueueUrl() {
      java.lang.Object ref = responseQueueUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseQueueUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string responseQueueUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getResponseQueueUrlBytes() {
      java.lang.Object ref = responseQueueUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseQueueUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 sendTime = 8;
    public static final int SENDTIME_FIELD_NUMBER = 8;
    private long sendTime_;
    /**
     * <code>optional int64 sendTime = 8;</code>
     */
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 sendTime = 8;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    // optional int64 receiveTime = 9;
    public static final int RECEIVETIME_FIELD_NUMBER = 9;
    private long receiveTime_;
    /**
     * <code>optional int64 receiveTime = 9;</code>
     */
    public boolean hasReceiveTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 receiveTime = 9;</code>
     */
    public long getReceiveTime() {
      return receiveTime_;
    }

    // optional int64 completeTime = 10;
    public static final int COMPLETETIME_FIELD_NUMBER = 10;
    private long completeTime_;
    /**
     * <code>optional int64 completeTime = 10;</code>
     */
    public boolean hasCompleteTime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 completeTime = 10;</code>
     */
    public long getCompleteTime() {
      return completeTime_;
    }

    // optional int64 finishTime = 11;
    public static final int FINISHTIME_FIELD_NUMBER = 11;
    private long finishTime_;
    /**
     * <code>optional int64 finishTime = 11;</code>
     */
    public boolean hasFinishTime() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 finishTime = 11;</code>
     */
    public long getFinishTime() {
      return finishTime_;
    }

    private void initFields() {
      taskId_ = 0L;
      clientId_ = 0L;
      workerId_ = 0L;
      taskType_ = "";
      bucketName_ = "";
      splitName_ = "";
      responseQueueUrl_ = "";
      sendTime_ = 0L;
      receiveTime_ = 0L;
      completeTime_ = 0L;
      finishTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBucketName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSplitName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, taskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, workerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTaskTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getBucketNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSplitNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getResponseQueueUrlBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, sendTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, receiveTime_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, completeTime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, finishTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, taskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, workerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTaskTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBucketNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSplitNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getResponseQueueUrlBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, sendTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, receiveTime_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, completeTime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, finishTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cloudmap.message.TaskMessage.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudmap.message.TaskMessage.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudmap.message.TaskMessage.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudmap.message.TaskMessage.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudmap.message.TaskMessage.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudmap.message.TaskMessage.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cloudmap.message.TaskMessage.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cloudmap.message.TaskMessage.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cloudmap.message.TaskMessage.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cloudmap.message.TaskMessage.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudmap.message.TaskMessage.Task prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudmap.message.TaskMessage.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudmap.message.TaskMessage.internal_static_Task_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudmap.message.TaskMessage.internal_static_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudmap.message.TaskMessage.Task.class, com.cloudmap.message.TaskMessage.Task.Builder.class);
      }

      // Construct using com.cloudmap.message.TaskMessage.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        taskId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        workerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        taskType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        bucketName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        splitName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        responseQueueUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        sendTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        receiveTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        completeTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        finishTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudmap.message.TaskMessage.internal_static_Task_descriptor;
      }

      public com.cloudmap.message.TaskMessage.Task getDefaultInstanceForType() {
        return com.cloudmap.message.TaskMessage.Task.getDefaultInstance();
      }

      public com.cloudmap.message.TaskMessage.Task build() {
        com.cloudmap.message.TaskMessage.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cloudmap.message.TaskMessage.Task buildPartial() {
        com.cloudmap.message.TaskMessage.Task result = new com.cloudmap.message.TaskMessage.Task(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.workerId_ = workerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.taskType_ = taskType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bucketName_ = bucketName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.splitName_ = splitName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.responseQueueUrl_ = responseQueueUrl_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.sendTime_ = sendTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.receiveTime_ = receiveTime_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.completeTime_ = completeTime_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.finishTime_ = finishTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudmap.message.TaskMessage.Task) {
          return mergeFrom((com.cloudmap.message.TaskMessage.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudmap.message.TaskMessage.Task other) {
        if (other == com.cloudmap.message.TaskMessage.Task.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasWorkerId()) {
          setWorkerId(other.getWorkerId());
        }
        if (other.hasTaskType()) {
          bitField0_ |= 0x00000008;
          taskType_ = other.taskType_;
          onChanged();
        }
        if (other.hasBucketName()) {
          bitField0_ |= 0x00000010;
          bucketName_ = other.bucketName_;
          onChanged();
        }
        if (other.hasSplitName()) {
          bitField0_ |= 0x00000020;
          splitName_ = other.splitName_;
          onChanged();
        }
        if (other.hasResponseQueueUrl()) {
          bitField0_ |= 0x00000040;
          responseQueueUrl_ = other.responseQueueUrl_;
          onChanged();
        }
        if (other.hasSendTime()) {
          setSendTime(other.getSendTime());
        }
        if (other.hasReceiveTime()) {
          setReceiveTime(other.getReceiveTime());
        }
        if (other.hasCompleteTime()) {
          setCompleteTime(other.getCompleteTime());
        }
        if (other.hasFinishTime()) {
          setFinishTime(other.getFinishTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskId()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        if (!hasTaskType()) {
          
          return false;
        }
        if (!hasBucketName()) {
          
          return false;
        }
        if (!hasSplitName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudmap.message.TaskMessage.Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudmap.message.TaskMessage.Task) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 taskId = 1;
      private long taskId_ ;
      /**
       * <code>required int64 taskId = 1;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 taskId = 1;</code>
       */
      public long getTaskId() {
        return taskId_;
      }
      /**
       * <code>required int64 taskId = 1;</code>
       */
      public Builder setTaskId(long value) {
        bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 taskId = 1;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 clientId = 2;
      private long clientId_ ;
      /**
       * <code>required int64 clientId = 2;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 clientId = 2;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>required int64 clientId = 2;</code>
       */
      public Builder setClientId(long value) {
        bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 clientId = 2;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 workerId = 3;
      private long workerId_ ;
      /**
       * <code>optional int64 workerId = 3;</code>
       */
      public boolean hasWorkerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 workerId = 3;</code>
       */
      public long getWorkerId() {
        return workerId_;
      }
      /**
       * <code>optional int64 workerId = 3;</code>
       */
      public Builder setWorkerId(long value) {
        bitField0_ |= 0x00000004;
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 workerId = 3;</code>
       */
      public Builder clearWorkerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        workerId_ = 0L;
        onChanged();
        return this;
      }

      // required string taskType = 4;
      private java.lang.Object taskType_ = "";
      /**
       * <code>required string taskType = 4;</code>
       */
      public boolean hasTaskType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public java.lang.String getTaskType() {
        java.lang.Object ref = taskType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          taskType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTaskTypeBytes() {
        java.lang.Object ref = taskType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public Builder setTaskType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public Builder clearTaskType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        taskType_ = getDefaultInstance().getTaskType();
        onChanged();
        return this;
      }
      /**
       * <code>required string taskType = 4;</code>
       */
      public Builder setTaskTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        taskType_ = value;
        onChanged();
        return this;
      }

      // required string bucketName = 5;
      private java.lang.Object bucketName_ = "";
      /**
       * <code>required string bucketName = 5;</code>
       */
      public boolean hasBucketName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string bucketName = 5;</code>
       */
      public java.lang.String getBucketName() {
        java.lang.Object ref = bucketName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bucketName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bucketName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBucketNameBytes() {
        java.lang.Object ref = bucketName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bucketName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bucketName = 5;</code>
       */
      public Builder setBucketName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bucketName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bucketName = 5;</code>
       */
      public Builder clearBucketName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bucketName_ = getDefaultInstance().getBucketName();
        onChanged();
        return this;
      }
      /**
       * <code>required string bucketName = 5;</code>
       */
      public Builder setBucketNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bucketName_ = value;
        onChanged();
        return this;
      }

      // required string splitName = 6;
      private java.lang.Object splitName_ = "";
      /**
       * <code>required string splitName = 6;</code>
       */
      public boolean hasSplitName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string splitName = 6;</code>
       */
      public java.lang.String getSplitName() {
        java.lang.Object ref = splitName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          splitName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string splitName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSplitNameBytes() {
        java.lang.Object ref = splitName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          splitName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string splitName = 6;</code>
       */
      public Builder setSplitName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        splitName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string splitName = 6;</code>
       */
      public Builder clearSplitName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        splitName_ = getDefaultInstance().getSplitName();
        onChanged();
        return this;
      }
      /**
       * <code>required string splitName = 6;</code>
       */
      public Builder setSplitNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        splitName_ = value;
        onChanged();
        return this;
      }

      // optional string responseQueueUrl = 7;
      private java.lang.Object responseQueueUrl_ = "";
      /**
       * <code>optional string responseQueueUrl = 7;</code>
       */
      public boolean hasResponseQueueUrl() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string responseQueueUrl = 7;</code>
       */
      public java.lang.String getResponseQueueUrl() {
        java.lang.Object ref = responseQueueUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          responseQueueUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responseQueueUrl = 7;</code>
       */
      public com.google.protobuf.ByteString
          getResponseQueueUrlBytes() {
        java.lang.Object ref = responseQueueUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseQueueUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responseQueueUrl = 7;</code>
       */
      public Builder setResponseQueueUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        responseQueueUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseQueueUrl = 7;</code>
       */
      public Builder clearResponseQueueUrl() {
        bitField0_ = (bitField0_ & ~0x00000040);
        responseQueueUrl_ = getDefaultInstance().getResponseQueueUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseQueueUrl = 7;</code>
       */
      public Builder setResponseQueueUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        responseQueueUrl_ = value;
        onChanged();
        return this;
      }

      // optional int64 sendTime = 8;
      private long sendTime_ ;
      /**
       * <code>optional int64 sendTime = 8;</code>
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 sendTime = 8;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>optional int64 sendTime = 8;</code>
       */
      public Builder setSendTime(long value) {
        bitField0_ |= 0x00000080;
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendTime = 8;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 receiveTime = 9;
      private long receiveTime_ ;
      /**
       * <code>optional int64 receiveTime = 9;</code>
       */
      public boolean hasReceiveTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 receiveTime = 9;</code>
       */
      public long getReceiveTime() {
        return receiveTime_;
      }
      /**
       * <code>optional int64 receiveTime = 9;</code>
       */
      public Builder setReceiveTime(long value) {
        bitField0_ |= 0x00000100;
        receiveTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 receiveTime = 9;</code>
       */
      public Builder clearReceiveTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        receiveTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 completeTime = 10;
      private long completeTime_ ;
      /**
       * <code>optional int64 completeTime = 10;</code>
       */
      public boolean hasCompleteTime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 completeTime = 10;</code>
       */
      public long getCompleteTime() {
        return completeTime_;
      }
      /**
       * <code>optional int64 completeTime = 10;</code>
       */
      public Builder setCompleteTime(long value) {
        bitField0_ |= 0x00000200;
        completeTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 completeTime = 10;</code>
       */
      public Builder clearCompleteTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        completeTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 finishTime = 11;
      private long finishTime_ ;
      /**
       * <code>optional int64 finishTime = 11;</code>
       */
      public boolean hasFinishTime() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 finishTime = 11;</code>
       */
      public long getFinishTime() {
        return finishTime_;
      }
      /**
       * <code>optional int64 finishTime = 11;</code>
       */
      public Builder setFinishTime(long value) {
        bitField0_ |= 0x00000400;
        finishTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 finishTime = 11;</code>
       */
      public Builder clearFinishTime() {
        bitField0_ = (bitField0_ & ~0x00000400);
        finishTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Task)
    }

    static {
      defaultInstance = new Task(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Task)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTask.proto\"\336\001\n\004Task\022\016\n\006taskId\030\001 \002(\003\022\020\n" +
      "\010clientId\030\002 \002(\003\022\020\n\010workerId\030\003 \001(\003\022\020\n\010tas" +
      "kType\030\004 \002(\t\022\022\n\nbucketName\030\005 \002(\t\022\021\n\tsplit" +
      "Name\030\006 \002(\t\022\030\n\020responseQueueUrl\030\007 \001(\t\022\020\n\010" +
      "sendTime\030\010 \001(\003\022\023\n\013receiveTime\030\t \001(\003\022\024\n\014c" +
      "ompleteTime\030\n \001(\003\022\022\n\nfinishTime\030\013 \001(\003B#\n" +
      "\024com.cloudmap.messageB\013TaskMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Task_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Task_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Task_descriptor,
              new java.lang.String[] { "TaskId", "ClientId", "WorkerId", "TaskType", "BucketName", "SplitName", "ResponseQueueUrl", "SendTime", "ReceiveTime", "CompleteTime", "FinishTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
